services:
    postgres:
      image: postgres
      networks:
        - local-app
      environment:
        POSTGRES_PASSWORD: 123456
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
        - ./init-scripts:/docker-entrypoint-initdb.d/
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        retries: 5
        start_period: 10s
    phpmyadmin:
      image: dpage/pgadmin4
      networks:
        - local-app
      depends_on:
        - postgres
      ports:
        - "9000:80"
      environment:
        PGADMIN_DEFAULT_PASSWORD: 123456
        PGADMIN_DEFAULT_EMAIL: root@gmail.com
    redis:
        image: redis
        networks:
            - local-app
        ports:
            - "6380:6379"
    test-soa:
      image:  duongsonn/sondth-test-soa:latest
      networks:
        - local-app
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_started
      ports:
        - "3000:3000"
      volumes:
        - ./volumes/test-soa:/app/logs

networks:
    local-app:
        driver: bridge
